name: 'Build Wasm Binary'
description: 'Builds a wasm binary package from the source package'
inputs:
  sourcepkg:
    description: 'Filename of the source package'
    required: true
outputs:
  binarypkg:
    description: 'Filename of the wasm binary package (if successful)'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/r-universe-org/build-wasm'
  env:
    SOURCEPKG: ${{ inputs.sourcepkg }}
